### ISSUE TITLE
Error handling during domain creation

### ISSUE THREAD

**Issue by stedolan** [ocaml-multicore/ocaml-multicore#129]
If a new domain can't allocate enough memory to start, then `Domain.spawn` should raise an exception. Currently, it kills the whole runtime.

**Comment by rmdouglas** [comment]
I've looked further into implementing a solution to this issue, and to me it looks like there's 2 real options:
 - Create a "dummy" exception handler on the stack (setsigjmp for bytecode, create a c_stack and exn_handler for native code).
- Make sure that the operations called from create_domain cannot raise an ocaml exception (by, for example, calling caml_stat_alloc_noexn instead of caml_alloc_stat).

To me the first is more complicated (bytecode is simple enough). Apart from a call to caml_create_root (which calls caml_alloc_shr, which has no '_noexn' counterpart) the other functions call caml_stat_alloc and should be amenable to switching to caml_stat_alloc_noexn and indicating an error (via returning NULL, or an error value, etc).

Does anyone have any further thoughts or opinions on the options I can see, or has better ideas for a solution?

**Comment by rmdouglas** [comment]
Another option could be to somehow install the parent domain's exception handler(s) in the child domain while it is initializing, though I don't know if that would be simpler than installing "dummy" exception handlers, nor how it might cause issues due to the exception crossing domain boundaries.

**Comment by kayceesrk** [comment]
Fixed by #264.
