### ISSUE TITLE
Controlled memory usage (as Racket's custodians)

### ISSUE THREAD

**Issue by takanuva** [ocaml-multicore/ocaml-multicore#179]
Could anyone argue on how difficult it would be to change the garbage collector so that I could isolate the memory usage of a code section? E.g., "run function foo () with 20mb of RAM maximum", similar to custodians in Racket.

(My particular scenario is research on compilers as services; I want to build a compiler that may be accessed through a web API, but malicious input could consume too much memory and time, so I'd like to impose per user limits. Racket's cool, but OCaml with effects is awesome.)

Also, would such a feature be of any interest to the community? If I go through and take some time to implement it, should I open a pull request?

**Comment by kayceesrk** [comment]
Hi @takanuva. Perhaps one way to do this is to run `foo()` in a handler, which gets is own fiber (the runtime stack segment that represents the delimited continuation of `foo()`. The fiber data structure has [a few fields at the top of stack](https://github.com/ocamllabs/ocaml-multicore/blob/master/byterun/caml/fiber.h#L37) for bookkeeping. You could think about adding an extra field which keeps tracks of the allocations. 

There are several advantages to this scheme. Firstly, by running `foo()` in its own stack, you can track the stack usage along with the heap usage; you don't want the malicious input to stack overflow and kill the program. Secondly, you can amortise the cost of bookkeeping by only recording allocations at context switch points for minor allocations (the majority) and bookkeeping at major allocations (minority). 

However, the cost of bookkeeping might be expensive for the default case; even code that doesn't use memory limit will have extra branches added to the allocation path. It would have to be seen whether you can make the overheads low enough for this feature to be enabled by default. Perhaps you can imagine this feature to be enabled by a compile time flag. Moreover, running `foo()` within its own handler allows a path to safely recover when you hit the memory limit. Here is an example with a hypothetical syntax extension:

```ocaml
let m = ref 4096 in
let max = 2621440 in
try foo() limit !m with 
| effect OutOfMemory k ->
    m := 2 * !m;
    if !m > max then 
        print_string "Out of memory\n"
    else begin
        printf "Increasing limit to %d\n" !m;
        set_limit k !m;
        continue k ()
    end
```

Regarding upstreaming such a feature, there would have to be wider consensus from the OCaml folks, since the proposed feature isn't necessarily tied to the Multicore OCaml project.

**Comment by lpw25** [comment]
Before anyone starts implementing anything, I think it is worth considering whether such a feature is really desirable. The issue here is that, as described, the feature seems to include some asynchronous interruption of running code -- i.e. when the section reaches its memory limit it is killed but other code in the process continues to run. OCaml already has some asynchrous interuptions (e.g. on stack overflow) but we are very seriously considering removing them.

The problem with asynchronous interruptions is that they make it extremely difficult -- well actually impossible with OCaml at the moment -- to write robust resource-safe code. If code can cease running at any time then you cannot ensure, for example, that an opened file is always closed and close is never called on an unopened file.

There are two main alternatives to this kind feature:
1. Use processes for the constrained "sections". This avoids the problems because the thing that is killed does not share OS resources or memory with anything else.
2. The code in the "section" synchronously kills itself at a safe-point. For example, if OCaml had a feature that could track the amount of memory allocated by a particular fiber and its children, then your compiler could periodically check that amount and raise an exception if it was over the given limit.

Both of these approaches seem to be viable solutions for your specific use-case, whilst giving much better semantics from the point of view of resource management.

**Comment by takanuva** [comment]
Thank you both for the feedback. Is the garbage collector itself asynchronous? (I haven't read the paper yet, sorry.) As I picture it, an effect would be synchronously thrown when trying to allocate an object that, even after garbage collection, would exceed the imposed limit, similar to @kayceesrk's example. I'll take a look at the runtime, but hopefully this may be done without causing performance impact on code that doesn't use a resource limit.

I'd also like to see what the OCaml community thinks about such a feature, it would be nice to have it upstream. I think this is mostly useful for running complex algorithms on untrusted input, specially for web servers, as I explained my use case. Racket argues that [their environment might spawn graphical applications that could break the whole system](https://www2.ccs.neu.edu/racket/pubs/icfp99-ffkf.pdf), so they added this feature to their runtime.

**Comment by lpw25** [comment]
Throwing an effect or exception on an allocation counts as asynchronous for these purposes. Basically all the problems regarding asynchronous interruptions still hold.

The existing asynchronous interrupts in OCaml that I mentioned also only happen on allocations. Since allocations make up a huge proportion of instructions, and are very difficult to program around, its not very far from saying that the interrupt can occur on any instruction.

**Comment by takanuva** [comment]
You suggested that a section (I'm assuming a `try`/`with`) could synchronously kill itself. Could you elaborate on that?

**Comment by lpw25** [comment]
I just mean something like:
```
let check_limit () =
  if allocated_in_this_section () > limit then raise Limit_exceeded
```
and then the compiler would call `check_limit` in periodically. It's obviously more work for the compiler implementer, but it is much clearer where this exception can occur. There isn't currently a mechanism for implementing `allocated_in_this_section`, but I think you could implement one using a similar approach to what KC was describing.

**Comment by gadmm** [comment]
(@stedolan If you are interested in continuing to discuss the OOM issue at some point, this is one of the ideas I had in mind.)

Leaving aside the question of safely managing resources in the presence of asynchronous exceptions, this idea could lead to a reliable Out_of_memory exception on minor allocation without having to backtrack from a failed minor collection. The idea is a bit similar to per-thread allocation limits in Haskell (https://simonmar.github.io/posts/2017-01-24-asynchronous-exceptions.html).

Fiber-local memory limits address the problem of the locality of Out_of_memory. In addition, it makes Out_of_memory on minor allocations a true asynchronous exception, in the sense that it can be delayed. This is good, because it reduces the problem of safely managing resources to the general problem of asynchronous exceptions (concretely you do not have to care about minor allocations during the acquisition and release of resources in `bracket`-style resource-management, which is something that I used to worry about). I expect it to cover at least some of the use-cases of OOM recovery.

@takanuva : memory limits are implemented by msat and archsat, but it is limited to global memory usage (see https://github.com/Gbury/mSAT/blob/40464e4fe713abcc1b9ee68e44c88288e041e5d5/src/main/main.ml#L143-L159).
