### ISSUE TITLE
Improve Lazy implementation

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#230]
Based on comments here: https://github.com/ocamllabs/ocaml-multicore/pull/226#issuecomment-433344032

**Comment by anmolsahoo25** [comment]
So after my initial look, I think I have managed to figure out the changes required - 

1. Change the Lazy block value creation from `Assignment` to `Heap_initialization` here - 
https://github.com/ocaml-multicore/ocaml-multicore/blob/8fbacb11cc91d6f8d5a64a7b335a8c2d97480e52/bytecomp/translcore.ml#L1084

2. Change this C function such that the old tag value is not provided, as the only time we would be using this function is for marking the block from `Lazy` to `Forward`. 
https://github.com/ocaml-multicore/ocaml-multicore/blob/8fbacb11cc91d6f8d5a64a7b335a8c2d97480e52/byterun/obj.c#L58

**Comment by stedolan** [comment]
Sounds good to me! The corresponding change has already been made in trunk in https://github.com/ocaml/ocaml/pull/1725, so it would be good to remain similar. (In particular, please use the same name for the primitive, `caml_obj_make_forward`, as primitives with different names cause boostrapping / merging pain).

**Comment by anmolsahoo25** [comment]
Thank you for the pointers. I will get to it.

**Comment by anmolsahoo25** [comment]
So as it stands for the multicore repo, the tag update and field update are done by 2 separate functions - `Obj.set_field` and `Obj.cas_tag`.

https://github.com/ocaml-multicore/ocaml-multicore/blob/8fbacb11cc91d6f8d5a64a7b335a8c2d97480e52/stdlib/camlinternalLazy.ml#L46-#L47

If we implement the `caml_obj_forward` as this  -

https://github.com/ocaml/ocaml/blob/6babd25e3a6e54e3122ed9f8423e7d41f4751588/runtime/obj.c#L75-#L80

Then a few changes in the `stdlib` would be required. Would it be better to go this route? Or would it be better to just specialize `caml_cas_tag` to `caml_obj_forward` as it is being used right now.

**Comment by stedolan** [comment]
I think it would be best to make multicore and trunk as similar as possible, and it's OK to make changes to multicore stdlib. I don't think the issues are serious:

1. `caml_modify(&Field(a, b), c)` on trunk is the same as `caml_modify_field(a, b, c)` on multicore. Both call the same amount of write barriers. (The syntax `&Field` doesn't work on multicore, so that's the equivalent)

2. `Parraysetu` gets compiled as a call to `caml_modify_field` anyway, so I don't think there's any problem doing both of the calls from C. (See `addr_array_set` in `asmcomp/cmmgen.ml`)

**Comment by anmolsahoo25** [comment]
All right. That sounds good. Then I will make these changes and create a PR.
