### ISSUE TITLE
Atomic.get should be inlined on x86

### ISSUE THREAD

**Issue by sadiqj** [ocaml-multicore/ocaml-multicore#237]
On x86 Atomic.get is a `mov` and should probably be inlined as such.

Consensus so far seems to be to leave it as a primitive right until emit.mlp, and on x86 turn that into a `mov` but on other platforms leave it as a call into C.

**Comment by kayceesrk** [comment]
@anmolsahoo25 is looking at this issue. I've put done some thoughts about the implementation for the sake of getting started. 

On x86, which is the only platform supported by multicore,  `Atomic.get` translates to a `mov` instruction [1]. `Atomic.get` is also a read. So a read barrier is required on the result of the read. The current implementation implements `Atomic.get` as an external call `caml_atomic_load` [2], which unconditionally invokes the read barrier, which should be optimized so that read barrier is only invoked when the value stored in the atomic reference is a pointer type [3].

Given these constraints, the cleanest way to translate `Atomic.get` is to 

0. Extend `Patomic_load` to `Patomic_load of immediate_or_pointer`. See `Pfield` in `lambda.mli` for reference. 
1. `Cload` and `Cloadmut` to have an extra parameter `is_atomic : bool` which captures whether the load is on an atomic location. 
2. Translate `Patomic_load Immediate` to `Cload (m, Mutable, Atomic)`, where `m` is the memory_chunk
3. Translate `Patomic_load Pointer` to `Cloadmut Atomic` if the value stored in the atomic reference is a pointer. 
4. For x86, you can ignore the atomicity parameter of `Cload` and `Cloadmut`. On other architectures, we'll need to insert appropriate synchronization. 

With the above, atomic refs storing immediate values will be translated to plain `mov` and those storing pointers will be translated to a `mov` followed by a read barrier on the result. 

[1] http://kcsrk.info/papers/pldi18-memory.pdf Table 3. 
[2] https://github.com/ocaml-multicore/ocaml-multicore/blob/ea0a7f19d0ebed7f343a7dd01b0b8e1ae72bde29/byterun/memory.c#L230-L243
[3] https://github.com/ocaml-multicore/ocaml-multicore/blob/master/asmcomp/cmm.mli#L101

**Comment by anmolsahoo25** [comment]
So just to make it a bit more clear, if I have understood the problem (since I am new to this overall!), I am attaching a few notes below - 

If we compile this fragment of code - 

```ocaml
(* test.ml *)

(* Creating an atomic ref *)
let x = Atomic.make false

(* Getting the value of atomic ref *)
let y = Atomic.get x
```

And compile it using - 

```bash
ocamlopt -S test.ml
```
We get the following asm of interest, (with certain parts redacted, for conciseness),

```asm
...

.L100:
	movq	camlTest@GOTPCREL(%rip), %rbx
	movq	%rax, (%rbx)
	movq	(%rbx), %rdi
	movq	caml_atomic_load@GOTPCREL(%rip), %rax
	call	caml_c_call@PLT
...
```
Depending on whether the load is to a value or pointer, we would want to inline the caml_atomic_load at this location.

**Comment by kayceesrk** [comment]
We would want to inline the `caml_atomic_load` to a `mov` if immediate or a `mov` followed by a read barrier if pointer. Hence the suggestion to compile `Patomic_load` to `Cload` or `Cloadmut`.
