### ISSUE TITLE
caml_obj_make_forward when not alone results in an infinite loop

### ISSUE THREAD

**Issue by sadiqj** [ocaml-multicore/ocaml-multicore#273]
https://github.com/ocaml-multicore/ocaml-multicore/blob/c32672116dd9106701df115d3bbfcfdaeb675993/byterun/obj.c#L58-L80

Line 65 in the above applies some masking to the value of `hd_lazy` such that the following `atomic_compare_exchange_strong` will always fail. The second parameter to `atomic_compare_exchange_strong` should be the expected value of the header (that is without the masking).

**Comment by kayceesrk** [comment]
Good catch. The code is broken. There should be `Int_val` around the tags. `Int_val` used to be in the old code since we were taking in the tags are arguments earlier (See https://github.com/ocaml-multicore/ocaml-multicore/blob/c52c79038567fa65279e68c7626edbc3e07efe2d/byterun/obj.c#L58-L79). The new code seems to have incorrectly retained the `Int_val`.

Moreover, we know that the code is only applied to `Lazy_tag` values. Hence, the updated code `hd_lazy = hd_lazy = (Hd_val(blk) & ~0xFF) | Lazy_tag; ` will only work on Lazy_tag objects. Indeed, the function is expected to be called only on Lazy_tag objects. So the masking is unnecessary, but it would be useful to add an assertion. I'll propose a fix shortly.
