### ISSUE TITLE
How should one work on optimizing a small Multicore-using program?

### ISSUE THREAD

**Issue by gasche** [ocaml-multicore/ocaml-multicore#324]
Dear multicore people,

Last Sunday I decided to distract myself by trying out OCaml Multicore. I picked a random benchmark from the Shootout with a parallel OCaml version (using Unix.fork) and ported it to use Domains instead. Here (following the advice [from KC on Discuss](https://discuss.ocaml.org/t/multicore-ocaml-march-2020-update/5406/18?u=gasche)) I am posting the code, some benchmark numbers, and I am asking about:
1. How to go at improving the performance. It is not as fast as the `Unix.fork` version yet, how do I get a sense of what should be improved?
2. Where is the library support that I could reuse to write efficient versions (without reimplementing my own load-balancing or whatever), or if they are still missing where should they go?

## The program

I chose [binary-trees](https://benchmarksgame-team.pages.debian.net/benchmarksgame/program/binarytrees-ocaml-2.html). My code is available at <https://gitea.lakaban.net/gasche/multicore-shootout/src/branch/master/binary-tree>. It includes the shootout version, and then three versions that depend only in how `schedule : ('a -> 'b) -> 'a array -> 'b array` is implemented: a sequential implementation, the Unix.fork implementation (whose performance are virtually identical to the shootout version), my `multicore.ml` version.

I found out after writing my version that there already is a Multicore version of this program in Sandmark:  [multicore-numerical/binarytrees5_multicore.ml](https://github.com/ocaml-bench/sandmark/blob/master/benchmarks/multicore-numerical/binarytrees5_multicore.ml) (why multicore-numerical? there is already a shootout category in Sandmark benchmarks which would have been more discoverable.) The Sandmark version does not seem particularly better than my version, so I guess that advice on how to measure/optimize Multicore programs would be relevant there as well. I added it to my repository as `multicore_sandmark.ml`.

(This benchmark is an ideal case for `Unix.fork`-based parallelism as there is very little data to exchange between threads. The hope would be to do as well as this solution with Multicore, not necessarily to beat it -- although that should be possible in theory.)

## The numbers

```
Unix.fork version:
real 0m3.891s
user 0m10.599s
sys  0m0.469s

Multicore version (sandmark):
real 0m4.009s
user 0m10.521s
sys  0m0.252s

Multicore version (mine):
real 0m4.092s
user 0m8.793s
sys  0m0.426s

Sequential version:
real 0m6.814s
user 0m6.718s
sys  0m0.045s
```

## The code

Here is my fairly naive Multicore version of the `schedule` function.

```ocaml
let schedule (job : 'a -> 'b) (tasks : 'a array) : 'b array =
  let num_domains = try int_of_string (Unix.getenv "NUM_DOMAINS") with _ -> 3 in
  let worker worker_modulus () =
    tasks |> Array.mapi (fun i input ->
      if i mod num_domains <> worker_modulus then None
      else Some (job input)) in
  let workers =
    Array.init (num_domains - 1) (fun i -> Domain.spawn (worker i)) in
  let last_results = worker (num_domains - 1) () in
  let workers_results =
    Array.map Domain.join workers in
  let results = Array.map (fun _ -> None) tasks in
  let commit_results worker_results =
    worker_results |> Array.iteri (fun i -> function
      | None -> ()
      | Some output -> results.(i) <- Some output
    ) in
  Array.iter commit_results workers_results;
  commit_results last_results;
  Array.map (function None -> assert false | Some v -> v) results
```

I am splitting the tasks among domains in a naive way, with no attempt at load balancing. I suspect that this particular benchmark has reasonably balanced tasks, so this may not matter much. But of course I would be interested in using a better version (that sends tasks dynamically to worker domains as they become idles, for example by using a single multi-reader concurrent work-queue). Note that each task is relatively slow here (half a second?), so contention on the task-scheduling mechanism is not a problem.

## Where to find better code?

As far as I can tell, there is no implementation of this primitive (which is essentially `Parmap`) proposed for multicore. I think it would be nice to offer something, for example in Domainslib, not necessarily very sophisticated but at least something that exists. There is already a feature request for this, https://github.com/ocaml-multicore/domainslib/issues/2.

Are there pointers somewhere at where to go to implement slightly better versions this? Is there a recommended concurrent queue somewhere?

I found [Lockfree.Wsqueue](https://github.com/ocaml-multicore/lockfree/blob/master/src/lf_wsqueue.ml), but I don't particularly need a lock-free version, should I still use it? (Has it been tested to be reasonably efficient?)

## The main question

I have my simple Multicore program and it is slower than I would like (than the Unix.fork version). How do I go around understanding where the performance difference is spent? Should I sprinkle calls to `Unix.gettimeofday()` and debug prints (is there a preferred way to print in a non-racy way?), to look at the duration of each task? Is there a magical solution like a multicore-aware version of Landmarks, or a multicore version of Eventlog tracing that I can get to get nice traces of my `schedule` scheduling strategy? Am I wrong in assuming that load-balancing is what makes the difference, and should I look at something else?

Thanks for your exciting playground!

**Comment by gasche** [comment]
After looking around, it looks like [Domainslib.Chan](https://github.com/ocaml-multicore/domainslib/blob/master/lib/chan.ml) is actually a reasonable first thing to use for a concurrent work-queue: create an unbounded channel and push all work items on it, then have each domain (plus the main worker) receive. It wasn't immediately obvious to me because all the code I found (for example Sandmark's multicore version of binary-trees) uses Chan for single-sender single-receiver channels, and the .mli documentation which I looked at does not make this point very explicit.

**Comment by gasche** [comment]
There you go:

```ocaml
let schedule (job : 'a -> 'b) (tasks : 'a array) : 'b array =
  let num_domains = try int_of_string (Unix.getenv "NUM_DOMAINS") with _ -> 3 in
  let module Chan = Domainslib.Chan in
  
  (* shared communication of jobs and results *)
  let work_queue = Chan.make max_int in
  let result_queue = Chan.make max_int in

  (* worker loop *)
  let exception Stop in
  let rec worker () =
    let work = Chan.recv work_queue in
    match work () with
    | exception Stop -> ()
    | result ->
      Chan.send result_queue result;
      worker ()
  in

  (* push all tasks *)
  tasks |> Array.iteri (fun i input ->
    Chan.send work_queue (fun () -> (i, job input)));
  (* schedule as many Stops as we will have workers *)
  for _ = 1 to num_domains do
    Chan.send work_queue (fun () -> raise Stop);
  done;

  (* run all the workers *)
  let children = Array.init (num_domains - 1) (fun i -> Domain.spawn worker) in
  worker ();
  Array.iter Domain.join children;
  (* at this point all workers are done *)

  (* collect results *)
  let results = Array.map (fun _ -> None) tasks in
  tasks |> Array.iter (fun _ ->
    let (i, output) = Chan.recv result_queue in
    results.(i) <- Some output;
  );
  Array.mapi (fun i -> function None -> assert false | Some v -> v) results
```

(Essentially the same numbers as before, but should help for more heterogeneous tasks.)

**Comment by gasche** [comment]
In fact, if I understand correctly, separate domains can write to distinct elements of an array, this is not racy. I could simplify to the following:

```ocaml
let schedule (job : 'a -> 'b) (tasks : 'a array) : 'b array =
  let num_domains = try int_of_string (Unix.getenv "NUM_DOMAINS") with _ -> 3 in
  let module Chan = Domainslib.Chan in

  (* shared communication of jobs and results *)
  let work_queue = Chan.make max_int in
  let results = Atomic.make (Array.map (fun _ -> None) tasks) in

  (* worker loop *)
  let exception Stop in
  let rec worker () =
    let work = Chan.recv work_queue in
    match work () with
    | () -> worker ()
    | exception Stop -> ()
  in

  (* push all tasks *)
  tasks |> Array.iteri (fun i input ->
    Chan.send work_queue (fun () ->
      let result = job input in
      (Atomic.get results).(i) <- Some result));
  (* schedule as many Stops as we will have workers *)
  for _ = 1 to num_domains do
    Chan.send work_queue (fun () -> raise Stop);
  done;

  (* run all the workers *)
  let children = Array.init (num_domains - 1) (fun i -> Domain.spawn worker) in
  worker ();
  Array.iter Domain.join children;
  (* at this point all workers are done *)

  Atomic.get results |> Array.map (function
    | None -> assert false
    | Some v -> v)
```

I have the impression that this version is faster than Sandmark's, and not clearly slower than the Unix.fork one (the difference could be in the noise).

**Comment by gasche** [comment]
Grmbl; I should have read the gram_matrix benchmark more carefully, this single-sender-multi-receiver pattern is also what @kayceesrk used [there](https://github.com/ocaml-bench/sandmark/blob/90acbf5/benchmarks/multicore-grammatrix/grammatrix_multicore.ml).

The pattern of having to be careful to close all the worker listening on the common channel is a bit irritating, and it may not work very well in more dynamic scenarios where the number of listeners is not known precisely. Maybe it would be possible to extend `Domainslib.Chan` to be able to "close" a channel? (The problem is to define races between closing and sending; I think that sending on a closed channel should be an error.)

**Comment by kayceesrk** [comment]
Hi @gasche. Thanks for giving multicore a try and for the contributions. The questions that you have raised are very relevant. Much of the support is available, but no documentation is available. @sudha247 is specifically looking at improving documentation of multicore ecosystem. 

## Binarytrees Benchmark

First off, something about the benchmark. As the benchmark [description](https://benchmarksgame-team.pages.debian.net/benchmarksgame/description/binarytrees.html#binarytrees) says, the binary trees benchmark is specifically designed to test the performance of the allocator and the GC and is an adaptation of [Boehm's GCBench](https://hboehm.info/gc/gc_bench/GCBench.c). The `Unix.fork` version does not pay the overhead of multithreaded allocation and GC. Hence, I would expect the multicore version to be slower here. Multicore will win when there is fine-grained synchronization or when the program dictates sharing large objects between the different processes in `Unix.fork` (leading to marshaling overheads which are not present in multicore).

## On channels

I agree that channel implementation lacks documentation. We'll work on improving it. The channels are multi-sender multi-receiver channels modeled on buffered channels in Go (but also CML channels (buffer size is 0), and GHC Haskell MVars (buffer size 1)). The channels are first-class values and are GCed. If the main thread terminates, then the program terminates. Hence, It is not strictly necessary to cleanly close the channels in this benchmark, but it is good practice in general.  `close` can be implemented reasonably efficiently, but given the fixed number of domains, we should be able to reasonably express termination similar to [Grammatrix](https://github.com/ocaml-bench/sandmark/blob/master/benchmarks/multicore-grammatrix/grammatrix_multicore.ml). 

I do not plan to provide selective communication (similar to Go select and CML select/choose) at this level since selective communication adds a lot of overhead even if the program only uses send and receive. Moreover, selective communication makes sense for user-level threads where you may have thousands of them rather than domains which is expected to be a small fixed number.

## Performance debugging

For performance debugging, we use perf and eventlogs. You can run

```bash
$ perf record ./binarytrees_multicore.exe 4 20
$ perf report
```

which displays a report similar to

![image](https://user-images.githubusercontent.com/410484/78630319-09fac880-78b7-11ea-9e86-62f70cb156ea.png)

which you can dig in further:

![image](https://user-images.githubusercontent.com/410484/78630379-3282c280-78b7-11ea-9e4c-bf83964ed0b5.png)

You can also generate eventlogs with 

```
$ OCAMLRUNPARAM="e=1" ./binarytrees_multicore.exe 4 20
```

They are always enabled and do not need a separate runtime. Loading the eventlog file under `chrome://tracing` you'd get:

![image](https://user-images.githubusercontent.com/410484/78630910-7f1acd80-78b8-11ea-8601-673cdfe0436a.png)

which shows that work is generally balanced, but there's tons of GC going on and some domains are idle waiting for synchronization. 

(Note; It appears that I am running concurrent minor GC, and we've now made parallel minor the default one).

There are is also [an experimental script](https://github.com/ocaml-bench/sandmark/blob/master/pausetimes/process_eventlog.py) that allow you to process the event log and get the GC events that contributes to the maximum latency. One thing we've discovered with multicore program optimization is that identifying and fixing events that contribute to maximum latency improves throughput. For example, running the following command:

```
kc@church:~/repos/sandmark/_build/4.06.1+multicore+parallel_1/benchmarks/multicore-numerical$ python3 ~/repos/sandmark/pausetimes/process_eventlog.py foo eventlog.16343.json summary
{"name": "foo", "mean_latency": 1210944.3816942552, "max_latency": 28443132, "distr_latency": [1643, 2848, 5910, 12347, 30388, 113719, 457042, 2336664, 4018943, 5422204, 14504274, 20195588]}
28443132 Interval(1312830812, 1341273944, {'name': 'dispatch', 'overhead': 0, 'tid': 1})
23778085 Interval(1385542973, 1409321058, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
20195588 Interval(1342129886, 1362325474, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
18709327 Interval(1435010657, 1453719984, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
18578143 Interval(1416014367, 1434592510, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
18139757 Interval(968702138, 986841895, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
18128834 Interval(889954670, 908083504, {'name': 'dispatch', 'overhead': 0, 'tid': 1})
17261640 Interval(1188683917, 1205945557, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
17245697 Interval(1334845335, 1352091032, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
17068681 Interval(1193480554, 1210549235, {'name': 'dispatch', 'overhead': 0, 'tid': 1})
17034160 Interval(947883766, 964917926, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
16978896 Interval(1398624844, 1415603740, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
16335988 Interval(1258782416, 1275118404, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
16171970 Interval(1116411841, 1132583811, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
15831116 Interval(1045093930, 1060925046, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
15761682 Interval(1197650205, 1213411887, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
15656797 Interval(1331356242, 1347013039, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
15182185 Interval(236555597, 251737782, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
15149261 Interval(1275492750, 1290642011, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
15009776 Interval(221210973, 236220749, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
14741857 Interval(153826672, 168568529, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
14504274 Interval(77495456, 91999730, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
14489572 Interval(1327114211, 1341603783, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
14176135 Interval(1244239362, 1258415497, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
14163619 Interval(139328021, 153491640, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
13651899 Interval(1196414247, 1210066146, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
13548830 Interval(1359025248, 1372574078, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
13498473 Interval(1317323065, 1330821538, {'name': 'dispatch', 'overhead': 0, 'tid': 2})
13394272 Interval(1031303642, 1044697914, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
13133592 Interval(112719695, 125853287, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
12793435 Interval(208082311, 220875746, {'name': 'dispatch', 'overhead': 0, 'tid': 0})
12665612 Interval(1313775672, 1326441284, {'name': 'dispatch', 'overhead': 0, 'tid': 3})
```

Gives you a latency report. All the times are in nanoseconds. The first line

```
{"name": "foo", "mean_latency": 1210944.3816942552, "max_latency": 28443132, "distr_latency": [1643, 2848, 5910, 12347, 30388, 113719, 457042, 2336664, 4018943, 5422204, 14504274, 20195588]}
```

shows that the mean latency is 1.2ms, max is 28.4 ms. The array is latency percentiles `[10 %, 20%, 30%, 40% , 50%, 60%, 70%, 80%, 90%, 95%, 99%, 99.9%]`. For example, 99% of pauses are below 14.5 ms.

Subsequently, the report shows top 32 latency contributing events. The first one is:

```
28443132 Interval(1312830812, 1341273944, {'name': 'dispatch', 'overhead': 0, 'tid': 1})
```
where `28443132` is the latency in nanoseconds. `1312830812` is the starting time in nanoseconds. You can use this information to identify the event in eventlog. For example, here is that event:

![image](https://user-images.githubusercontent.com/410484/78633361-066b3f80-78bf-11ea-9e4d-3650dce1e476.png)

The starting time is a bit off (need to debug this), but the wall clock time is the same as the report. 

## Conclusion

I understand that much of what I've discussed is for multicore hackers to optimize the runtime. But I can see that by allowing OCaml users to insert their own start and end events, we can use the same tools for debugging user programs.

**Comment by gasche** [comment]
Thanks! This is super-useful and I would encourage you to move your answer to a more visible place. My plan for my next distraction period is to reproduce your profiling tricks with the various versions of the program to see the differences.

Note: the numbers I gave are all on my 4.06.1+multicore switch, so they should all (even the Unix.fork versions) use the Multicore GC. This is why I expect the Multicore version to be equivalent or faster to the Unix.fork version. (It is indeed a bit slower than the Unix.fork version on a non-multicore switch, but not what I was trying to measure here.) I would assume that using Unix.fork may have unpredictable benefits for performance (the kernel does some load scheduling which may be good in some cases), but also that it increases the memory consumption quite a bit (this example will run major GCs in many of the forks, which should unshare the large-persistent-tree even in COW implementations), so in theory Multicore should do better. But yes, this is one of the "best case scenarios" for Unix.fork, due to the very low amount of cross-task communication.

Looking at some other benchmarks from the shootout, it looks like some benchmarks use Unix.fork() because there was a simple parallelization approach that works well for `fork()`, and some others are harder to parallelize efficiently and are not parallelized at all (and there OCaml loses badly to other languages). I'm hoping that writing multicore version of those benchmarks could give nice gains, but that sort of assumes there are sensible parallelization primitives that are not too cumbersome to use. (Rewriting a parallel `Array.map` was fun but I wouldn't do it again for each new benchmark.)

I looked at the implementation of `Chan` when I started to implement `close`. It's nice, but I'm not completely convinced that it is important to support the `buffer_size = 0` case: it adds some complexity to the code, and I would assume that a dedicated size-0 implementation with the same operations would be simpler to implement and have lower constant factors (noticeably in high-usage scenarios).

**Comment by kayceesrk** [comment]
Even though the Unix.fork version is using the same GC, it doesn’t suffer from multicore synchronisation cost in the allocator; the allocator needs some tuning and we have an open PR #321 to address this. I would be curious to hear what you find in your next distraction period. In particular, I’d like to confirm my suspicions with hard evidence. 

> Rewriting a parallel Array.map was fun but I wouldn't do it again for each new benchmark.)

Agreed. Would be useful to add parallel array processing to Domainslib. 

> Thanks! This is super-useful and I would encourage you to move your answer to a more visible place

Glad you found it useful. I should move this to my blog :-)

**Comment by gasche** [comment]
Conclusion: with https://github.com/ocaml-multicore/domainslib/pull/4 merged there is now support for async/finish concurrency in Domainslib, which should be usable in many simple cases, see the current API of [Domainslib.Task](https://github.com/ocaml-multicore/domainslib/blob/2914213f/lib/task.mli) and the [test programs](https://github.com/ocaml-multicore/domainslib/tree/master/test) for examples:

```ocaml
let num_domains = try int_of_string Sys.argv.(1) with _ -> 1
let n = try int_of_string Sys.argv.(2) with _ -> 40

let rec fib n =
  if n < 2 then 1
  else fib (n-1) + fib (n-2)

module T = Domainslib.Task

let rec fib_par pool n =
  if n <= 40 then fib n
  else
    let a = T.async pool (fun _ -> fib_par pool (n-1)) in
    let b = T.async pool (fun _ -> fib_par pool (n-2)) in
    T.await pool a + T.await pool b

let main =
  let pool = T.setup_pool ~num_domains:(num_domains - 1) in
  let res = fib_par pool n in
  T.teardown_pool pool;
  Printf.printf "fib(%d) = %d\n" n res
```

(and @kayceesrk hasn't moved his excellent piece to his blog yet)

**Comment by kayceesrk** [comment]
> (and @kayceesrk hasn't moved his excellent piece to his blog yet)

On my list. I got distracted by how well the Task API fit this raytracer :-P https://github.com/athas/raytracers/pull/6

**Comment by gasche** [comment]
Would it help (assuming that you are not so excited about writing blog posts) if I proposed a quick restructuration of your post above, removing the irrelevant parts and adding some minor context so that it fits as a blog post more easily?

**Comment by kayceesrk** [comment]
Certainly. Please do.

**Comment by gasche** [comment]
(I sent a blog post draft by email to kc at kcsrk dot info.)

**Comment by kayceesrk** [comment]
Closing issue. @gasche Blog post is still on my list.
