### ISSUE TITLE
Parallel Array copy - performance 

### ISSUE THREAD

**Issue by Sudha247** [ocaml-multicore/ocaml-multicore#341]
This is an implementation of parallel array copy which does `Array.blit` on sub-parts of array in multiple domains.
```ocaml
module T = Domainslib.Task
let num_domains = try int_of_string Sys.argv.(1) with _ -> 4
let n = try int_of_string Sys.argv.(2) with _ -> 1024
let a = Array.make n 1.
let par_copy pool a =
  let copy_part a b i =
    let s = (i * n / num_domains) in
    let e = (i+1) * n / num_domains - 1 in
    Array.blit a s b s (e - s + 1) in
  let b = Array.create_float n in
  let rec aux acc num_domains i =
    if (i = num_domains) then
      (List.iter (fun e -> T.await pool e) acc)
    else begin
      aux ((T.async pool (fun _ -> copy_part a b i))::acc) num_domains (i+1)
    end
  in
  aux [] num_domains 0;
  b
let _ =
  let pool = T.setup_pool ~num_domains:(num_domains - 1) in
  let b = par_copy pool a in
  Printf.printf "\n%d" (Array.length b);
  T.teardown_pool
```
While analysing its performance, I observed a lot of `iTLB-load-misses` and `LLC-load-misses`. Just to be sure this is not caused by the Task API, I rewrote the above code to use only `Domainslib.Chan`. The stats were similar in both cases. Would be curious to know what is causing this and ways to potentially fix it. The following are stats on 4 cores for input `100_000_000`.
```
       1284.542030      task-clock (msec)         #    1.668 CPUs utilized
                21      context-switches          #    0.016 K/sec
                 3      cpu-migrations            #    0.002 K/sec
           391,191      page-faults               #    0.305 M/sec
     2,807,247,481      cycles                    #    2.185 GHz                      (69.27%)
     1,817,508,957      instructions              #    0.65  insn per cycle           (76.74%)
       315,014,121      branches                  #  245.235 M/sec                    (75.83%)
           808,875      branch-misses             #    0.26% of all branches          (74.90%)
       480,408,765      L1-dcache-loads           #  373.992 M/sec                    (74.83%)
        43,544,503      L1-dcache-load-misses     #    9.06% of all L1-dcache hits    (75.36%)
         1,069,223      LLC-loads                 #    0.832 M/sec                    (76.30%)
           423,890      LLC-load-misses           #   39.64% of all LL-cache hits     (77.42%)
   <not supported>      L1-icache-loads
           396,690      L1-icache-load-misses                                         (78.11%)
       472,529,236      dTLB-loads                #  367.858 M/sec                    (78.42%)
           407,676      dTLB-load-misses          #    0.09% of all dTLB cache hits   (63.54%)
               958      iTLB-loads                #    0.746 K/sec                    (63.23%)
           389,103      iTLB-load-misses          # 40616.18% of all iTLB cache hits  (62.07%)
       0.770119414 seconds time elapsed
```

**Comment by bluddy** [comment]
AFAIK, streaming data is one of the worst-case tests for multicore. There's very little to be gained by using >1 thread, except for saturating the memory bus. This is very easy to do since the act of copying a lot of data inherently keeps filling the cache with single-use data (each location is only written from once and written to once). Some architectures just disable the cache altogether when streaming data, so that whatever is relevant for other threads, or whatever action was done prior to the streaming, isn't evicted from the caches.

**Comment by anmolsahoo25** [comment]
Something is definitely wrong with the iTLB misses. I don't see how the number of misses can be greater than the total number of loads.

In the case of streaming data, the prefetcher should kick and even something as simple as next line prefetching would work well for streaming data. Intel processors have much more complicated pre-fetchers, so I assume they should handle this well. I will try to run it through Intel V-Tune and see if I get any insights. That tool should give some more analysis points.

**Comment by bluddy** [comment]
The numbers seem to mostly make sense given the task, and it looks like the prefetchers are working well: 480M loads from dcache, with only 10% misses (given the workload, it's good). 472M loads from tlb, with only 0.1% misses.

The only variable missing is how we get from 100M float loads + stores to 480M dcache loads. I'd be interested to know which path is taken in `caml_array_blit` (https://github.com/ocaml/ocaml/blob/10561873487c185c0727f08b26706226dbb1a7b6/runtime/array.c). It's possible that the memory is copied in 32-bit chunks, which would double the loads. It's also possible that an even slower path is followed.

**Comment by stedolan** [comment]
Perf makes a few odd choices for names of events. I think it's perfectly possible for iTLB-load-misses to exceed iTLB-loads [see here](https://stackoverflow.com/questions/49933319/how-to-interpret-perf-itlb-loads-itlb-load-misses).

Which exact model of CPU are these numbers from?

**Comment by Sudha247** [comment]
The numbers are from Intel Xeon Gold 5120 (28 Cores, 14 Cores per socket) with hyperthreading turned off and cores isolated.

**Comment by anmolsahoo25** [comment]
@stedolan Thanks! That is surprising.

**Comment by stedolan** [comment]
Because Linux tries to pick cross-platform names for the values in perf stat, working out what the numbers actually mean is a long slog. Here goes:

First, figure out which microarchitecture you're using. You can look up the processor on [ark.intel.com](https://ark.intel.com/content/www/us/en/ark/products/120474/intel-xeon-gold-5120-processor-19-25m-cache-2-20-ghz.html), look under "Code Name". Here it's Skylake.

Next, figure out which performance counter Linux calls "iTLB-load-misses" on this microarchitecture. You need to look at the kernel source for this, in [arch/x86/events/intel/core.c](https://github.com/torvalds/linux/blob/master/arch/x86/events/intel/core.c). (Or `amd/core.c` for AMD processors, but I'll assume Intel here).

On [Skylake processors](https://github.com/torvalds/linux/blob/master/arch/x86/events/intel/core.c#L5018-L5067), Linux uses the events defined in [skl_hw_cache_event_ids](https://github.com/torvalds/linux/blob/master/arch/x86/events/intel/core.c#L420-L523). If you look through this structure, you can see that iTLB accesses and misses are defined as:

```
 [ C(ITLB) ] = {
	[ C(OP_READ) ] = {
		[ C(RESULT_ACCESS) ] = 0x2085,	/* ITLB_MISSES.STLB_HIT */
		[ C(RESULT_MISS)   ] = 0xe85,	/* ITLB_MISSES.WALK_COMPLETED */
	},
```

To figure out what these mean, you need to consult the [Intel processor manuals](https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html). Specifically, [Volume 3B](https://software.intel.com/content/www/us/en/develop/download/intel-64-and-ia-32-architectures-sdm-volume-3b-system-programming-guide-part-2.html) has the performance event definitions.

Skylake is in Table 19-3 and explains that ITLB_MISSES.WALK_COMPLETED counts completed page walks that "missed ITLB and further levels of TLB" while ITLB_MISSES.STLB_HIT counts "Instruction fetch requests that miss the ITLB and hit the STLB."

To understand the acronyms, you can read another massive PDF, the [Intel Optimization Manual](https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-optimization-manual.pdf), which explains that the STLB is the second-level TLB, shared between instructions and data. (If you're not familiar with TLBs at all, [Wikipedia](https://en.wikipedia.org/wiki/Translation_lookaside_buffer) has an explanation. It caches lookups from pointers to hardware memory addresses).

So, confusingly, on this processor `iTLB-loads` means the number of instruction fetches that missed the first-level ITLB but hit the second level STLB, and `iTLB-misses` means the number of instruction fetches that missed the first-level TLB and then missed the STLB as well. (I have no idea why linux writes one as a percentage of the other).

Since iTLB-misses is much, much higher than iTLB-loads, it means that when an instruction fetch misses the first-level TLB it generally misses the rest as well. As the optimisation manual says, the STLB is shared between instructions and data, which suggests that most of the STLB slots contain data references most of the time, so there aren't many instruction hits there. This is what you'd expect if the program was accessing a large amount of data using a small amount of code, which is what's happening here: `Array.blit` on a huge array.

(If you're doing this a lot, I recommend installing [Andi Kleen's ocperf](https://github.com/andikleen/pmu-tools), which downloads the table of hardware events to save you looking them up in PDFs. There's a brief tutorial [on his blog](http://halobates.de/blog/p/245))

**Comment by Sudha247** [comment]
This is very helpful. Thanks @stedolan!

**Comment by Sudha247** [comment]
Stephen's comment above answers this, thanks again!
