### ISSUE TITLE
Preemptive multithreading

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#73]
Currently, we can only describe cooperative schedulers, where the fiber voluntarily yields control. In many cases, preemptive multi-threading makes sense. The standard way to do preemptive multi-threading in a system with user-level schedulers is to install an interval timer, handle the timer signal where the scheduler yields control to another runnable fiber. The equivalent code in OCaml might look something like:

```ocaml
open Sys
set_signal sigalrm (Signal_handle (fun _ ->
  let k = (* Get current continuation *) in 
  Sched.enqueue k;
  let k' = Sched.dequeue () in
  (* Set current continuation to k' *)));;

Unix.setitimer interval Unix.ITIMER_REAL
```

The trouble is that this solution is not compositional i.e) it breaks the nice abstraction that algebric effect handlers provide. For one, it is unclear where the signal handler actually runs. We somehow need to get hold of the current continuation (fiber) and switch control to a different fiber. However, the only way to get hold of a continuation in our system is at the handler. 

Ultimately, the signal handler is a callback. Algebric effect handlers help us avoid callback-oriented programming and instead express the same program in direct-style. Consider a `TimerInterrupt` effect:

```ocaml
effect TimerInterrupt : unit
  with function TimerInterrupt -> ()
```

whose default behaviour is to do nothing. We can now implement preemptive multithreading simply as a case in the scheduler handler:

```ocaml
let rec spawn f = 
  match f () with
  | () -> dequeue ()
  | effect Yield k -> yield k
  ...
  | effect TimerInterrupt k -> yield k

and yield k = enqueue k; dequeue ()
```

**Comment by lpw25** [comment]
It is worth noting that `TimerInterrupt` cannot be a typed effect, since it could appear at any allocation in the program.

**Comment by kayceesrk** [comment]
Does this mean that in a system with checked effects we would need unchecked effects as well to faithfully represent `TimerInterrupt`?

What class of effects does `TimerInterrupt` fall into? It cannot be a native `io` effect since this would mark all functions as performing IO. Is it an ambient effect like allocation, exceptions, non-termination? But unlike ambient effects, we not only can handle them but also get hold of the continuation (unlike exceptions).

**Comment by lpw25** [comment]
> Does this mean that in a system with checked effects we would need unchecked effects as well to faithfully represent TimerInterrupt?

Yes.

> What class of effects does TimerInterrupt fall into? It cannot be a native io effect since this would mark all functions as performing IO. Is it an ambient effect like allocation, exceptions, non-termination? But unlike ambient effects, we not only can handle them but also get hold of the continuation (unlike exceptions).

It is an "ambient" effect like exceptions and non-termination. If a function only "performs" `TimerInterrupt` and it returns a value then it will always return the same value -- since `TimerInterrupt` always returns `()` the only way to observe that you've been preemptively interrupted is through state. That is our definition of "pure" so `TimerInterrupt` is an ambient effect.

**Comment by bluddy** [comment]
Do we need preemptive multithreading? What's wrong with leaving it to the OS? Is this something that's desired, or just an exploration of the concept?

**Comment by kayceesrk** [comment]
The scenario we're considering is say N fibers on a single (and only) domain in an app. You'd like the N fibers to time share the domain. Since the OS does not see the fibers and only sees the domain, it is possible that a fiber may hog the domain if we do nothing. Timer interrupts handled explicitly by the fiber scheduler to yield the fibers get what we want.

**Comment by lpw25** [comment]
> Is this something that's desired, or just an exploration of the concept?

I think whether it is desired is up for debate, however it is worth noting that we are not adding any potential concurrency that isn't already there with `-threads`. So it doesn't make things worse in terms of reasoning about a program's behaviour. For those who prefer their concurrency cooperative the same approach that Async uses now -- i.e. a global lock to ensure only one async thread is running at a time -- will suffice to protect against unwanted thread switches.

> Does this mean that in a system with checked effects we would need unchecked effects as well to faithfully represent TimerInterrupt?

This is the part that most concerns me. The issue is the damage it does to our definition of a pure function. With type effects at the moment, a function that is typed pure will either return a value, return an exception or loop forever -- and multiple calls will do the same thing each time. This means that we can replace two calls to a pure function with a single call.

The only current complication is with exceptions like `Out_of_memory`, since they can appear arbitrarily. However, since they can appear arbitrarily and pure functions cannot affect the state of the program, you can always pretend that they were actually raised before or after the pure function was called -- essentially pretending that they live in `io` and only appear there.

Unchecked effects break these properties. A "pure" function can return a different value every time. It's the strongest argument I have that we shouldn't have both checked and unchecked effects within the language.

Now for `TimerInterrupt` we can kind of get away with the same thing as `Out_of_memory`. If the user isn't allowed to produce `TimerInterrupt` themselves then the semantics can always pretend that it appeared before or after the pure function was executed. However, if the user can perform `TimerInterrupt` deliberately within a pure function and then handle it then they may observe that there are fewer `TimerInterrupt`s performed than expected if we replace two invocations of a pure function with a single one.

So my suggestion would be that both performing and handling `TimerInterrupt` would be operations performing `io`. This would require `TimerInterrupt` to be treated specially by the type-checker since usually handling an effect is not an effectful operation (creating a continuation is but that's a separate issue). In fact, it might even be better to just have a:

```
match ... with
| interrupt, k -> ...
```

syntax. Then it would clearly be fine to treat it specially.

**Comment by lpw25** [comment]
A quick rebuttal to my own post.

> Unchecked effects break these properties. A "pure" function can return a different value every time. It's the strongest argument I have that we shouldn't have both checked and unchecked effects within the language.

This point is wrong. Obviously, unchecked effects are fine if performing them is in `io`.

So my suggestion is either:

1) Both performing and handling unchecked effects should be in `io`, and `TimerInterrupt` is an ordinary unchecked effect.

2) Performing unchecked effects is in `io` but handling them is pure. Then `TimerInterrupt` needs special support in the type checker -- possibly it should have its own syntax.

**Comment by bluddy** [comment]
If I understand it correctly then, this model would be much closer to the one used by haskell. It should really be termed pseudo-preemptive since true preemption can only be done at the OS level, and instead we pepper the code with implied cooperative yields. My question is then, why should this be visible to the programmer at all, rather than just making it transparent as it is for haskell.

**Comment by kayceesrk** [comment]
Because GHC Haskell's thread scheduler is a part of the runtime system. Runtime system schedules the haskell threads and can hence handle the preemption transparently. In multicore OCaml, fiber schedulers are written as OCaml libraries and the runtime system knows nothing about how to schedule them. In fact, the runtime system does not know what a scheduler is and does not see the scheduler queue any different from any other OCaml object on the heap. Hence, preemptive multithreading cannot be a transparent mechanism in multicore OCaml unlike GHC Haskell.

**Comment by domsj** [comment]
```
The scenario we're considering is say N fibers on a single (and only) domain in an app. You'd like the N fibers to time share the domain. Since the OS does not see the fibers and only sees the domain, it is possible that a fiber may hog the domain if we do nothing. Timer interrupts handled explicitly by the fiber scheduler to yield the fibers get what we want.
```

I don't understand the use case ... why wouldn't the user just create N domains that each run one fiber?

**Comment by bluddy** [comment]
@domsj Note that preemptive multithreading here does *not* mean multiple fibers running at once on a domain. At any point in time, only one fiber can be chosen to run on a domain. Rather than expecting the user to yield explicitly, we allocate only a certain time slice per thread, and insert invisible yield calls at certain places to check whether the time slice expired. The advantage is that code that isn't written to cooperatively yield can still yield to another fiber -- essentially all code becomes cooperative (at a cost).

This is how haskell manages green threading ('sparks'). The difference is that a haskell spark can easily move between domains, whereas in OCaml, this requires a minor GC cycle.

**Comment by kayceesrk** [comment]
> whereas in OCaml, this requires a minor GC cycle.

This is not quite true. A full minor GC is the worst case. In the average case, moving stack between domains requires work that is a small (single digit) percentage of the full minor gc work.

**Comment by bluddy** [comment]
> This is not quite true. A full minor GC is the worst case. In the average case, moving stack between domains requires work that is a small (single digit) percentage of the full minor gc work.

So you move the particular stack and everything it points to, and everything that points to etc and check the ref table? If you have many fibers in the domain, this may make sense, but otherwise a better heuristic may be to just do a minor GC.

**Comment by kayceesrk** [comment]
We currently employ a heuristic that chooses between promoting the transitive closure of the fiber + fixing any references to the promoted objects in the major heap/ref tables, and doing a minor GC. The heuristic uses the size of the minor heap to scanned after promotion. If this a few percentage of minor GC size, then we promote the fiber. Otherwise we choose to perform a minor GC. This is the same heuristic that is used for handling promotions on read barrier, when objects are promoted due to read requests from other domains.

**Comment by bartoszmodelski** [comment]
Has any conclusion about preemption been reached? 

In my opinion it would be a big win, and I'm happy to try to prepare a proposal with some proof-of-concept patch. 

It could work similarly to the current signal-handling code: register the trigger to yield (signal, timer expiration, ..), then perform yield effect at the nearest safepoint. The patch can target either safepoint assembly or try to (more generally) perform effect from C. The former would be much easier to reason about. The latter ~~was okay~~ didn't segfault in tests but it's naturally way scarier with so many moving parts (`C -> caml_callback_asm -> closure performing eff`). 

Also sorry for digging this up after so long - that's the most recent trace I found.
