### ISSUE TITLE
Scoped signal handling through effect handlers

### ISSUE THREAD

**Issue by kayceesrk** [ocaml-multicore/ocaml-multicore#91]
Signal handlers are callback functions which are invoked on the arrival of signals. They run asynchronously with respect to the main program, which makes them difficult to reason about. Algebraic effect handlers help us avoid callback-oriented programming and instead express the same program in direct-style. If signals were considered as ambient effects, then signal handlers are effect handlers. This provides us scoped signal handlers where the meaning of the signal is defined by the context in which it is handled. 

Consider an ambient signal effect:

```ocaml
let default_signal_handlers = 
  Array.init num_signals (fun _ -> failwith "impossible")

effect Signal : int 
  with function (Signal num) -> (default_signal_handlers.(num)) num
```

The signal effect has a default handler which runs the appropriate handler.  We change the behaviour of `Sys.set_signal sigid (Signal_handle callback)` [0] such that instead of registering the `callback` function, we update the corresponding entry in the default handler table. We also set up the runtime such that on the arrival of signal with number `n`, the effect `Signal n` is performed on the current fiber:

```ocaml
let set_signal signum = function
  | Signal_handle callback -> 
      default_signal_handlers.(signum) <- callback
      (* arrange for performing Signal effect *)
  | ... -> (* the same behaviour as vanilla OCaml *)
```

Now, if the signal effect is not handled, then the behaviour matches the behaviour of vanilla OCaml. However, since the effect `Signal num` can be handled, the programs will have the benefit of scoped signal handling. For example:

```ocaml
let _ = set_signal sigint (Signal_handle (fun _ -> print_endline "not in foo"))

let _ = 
  match foo () with
  | effect (Signal num) k when num = sigint -> 
      print_endline "in foo"; continue k ()
```

will print `in foo` if `sigint` was received while the execution is in `foo` and `not in foo` otherwise.

As with timer interrupts, signals cannot be typed effects. See https://github.com/ocamllabs/ocaml-multicore/issues/73. 

[0] http://caml.inria.fr/pub/docs/manual-ocaml/libref/Sys.html#6_Signalhandling

**Comment by lpw25** [comment]
I recently noticed an issue with this approach. What happens if a second signal is received when execution is here:

```ocaml
  match ... with
  | effect (Signal num) k when num = sigint -> 
      ...
      (* HERE *)
      ...
```

The effect handler semantics would result in this signal being dropped. I already thought that these kind of "asynchronous effects" needed their own syntax and typing, but it seems clear they would need a slightly different semantics as well, and it is not entirely clear to me that the `match` statement is the right way to express this other semantics.

**Comment by dbuenzli** [comment]
For me there's absolutely nothing "direct style" in this proposal: it only migrates the callback soup to the effect handler which you can equally do with the current API by setting up a handler for a given function execution scope `unwind-protect` style. That is a function `handle_signal sig h f ()` that setups the handler `h` for `sig` for the execution of `f ()`. 

I see things entirely the other way round: rather than have signals as an ambient effect that can occur at any time I would like to explicitly block waiting on a given signal in a fiber and be kontinued once the signal occurs. That would constitute a direct-style API in my opinion.

This means that signals are collected (the current API will do) by a runloop/scheduler abstraction that interprets effects. The abstraction would provide an `Await_signal of int` effect or a function `await_signal : int -> unit` that performs it. In my code I can then simply call this function, the scheduler will collect my continuation and invoke it only once the signal occurs at which point I can execute the logic that corresponds to the signal.

```ocaml
await_signal sig; 
(* this code is executed iff sig happened once since the last line was executed *) 
```

Note that this model corresponds exactly to what event loop libraries (e.g. `libevent`, `libuv`, osx `gcd`) do except that thanks to effects you don't need to write your continuation in a callback soup.

**Comment by dbuenzli** [comment]
> which you can equally do with the current API by setting up a handler for a given function execution scope unwind-protect style

Well you can't discard the continuation which effects would allow, but still that's not the model I would like to work with.

**Comment by bluddy** [comment]
Given the dropped signal problem, this seems to me like shoehorning something unrelated into effects just for the sake of doing 'something'. Better to keep the current effect design than try modifying it to fit this particular use case IMO.

**Comment by kayceesrk** [comment]
> I already thought that these kind of "asynchronous effects" needed their own syntax and typing, but it seems clear they would need a slightly different semantics as well, and it is not entirely clear to me that the match statement is the right way to express this other semantics.

The mental model that I have for the signal handling is that the default handler for the signal is always needed. The scoped signal handling is a refinement on top of this default handler. In your example, if the signal arrives in the body of the handler, then the signal bubbles up to the default handler. However, if a more expressive API was required [0], then I agree that `match...with` is not the right syntax. Are you thinking about this problem in particular?

> The abstraction would provide an Await_signal of int effect or a function await_signal : int -> unit that performs it. In my code I can then simply call this function, the scheduler will collect my continuation and invoke it only once the signal occurs at which point I can execute the logic that corresponds to the signal.

This synchronous API you've proposed here is the right one, but it is one abstraction level up. This API is what the I/O library might provide to the client, and similar to `sleep` in aeio library [1]. The question is how does the scheduler implement `await_signal`. You can indeed provide this API if you were using an eventloop underneath the hood. However, observe that this solution does not work for the cases when you truly need asynchronous signals, such as timer interrupt for preemptive multithreading. I really detest the idea of sharing mutable state (in this case, the scheduler queue) with the signal handler. I prefer the scheduler state explicitly passed around as argument in the scheduler queue [2]. For this reason, I think incorporating timer interrupts into the effect handler is a reasonable idea. The question is whether we should extend this to general signal handling. 

@bluddy See above. 

[0] https://www.gnu.org/software/libc/manual/html_node/Signals-in-Handler.html#Signals-in-Handler
[1] http://kcsrk.info/ocaml-aeio/doc/Aeio.html#VALsleep
[2] https://github.com/kayceesrk/ocaml-aeio/blob/master/src/aeio.ml#L406

**Comment by dbuenzli** [comment]
> The question is whether we should extend this to general signal handling.

I don't think this is a good idea. `await_signal` makes it easy to provide different interpreters for the requests. By doing this you can play or replay the environment of your program which is useful for simulating, testing, tracing, etc. 

Having many pervasive asynchronous effects and using effect handlers to handle these destroys the idea of seeing effects as a request/response interaction between a program and its context. By doing so you moved part of the program response handling logic to the context (the effect handlers). But the context should only be responsible to hand out the responses to the program and it is the latter that should handle them.

My feeling is that if there has to be an asynchronous interrupt effect there should be a single one and it doesn't need to be a "timer" one. Simply an `Interrupt` which can be used by schedulers both for preemptive multitasking and cancellation.

**Comment by stedolan** [comment]
@dbuenzli: `await_signal` is a much better interface for signal handling, and it's the one we should expose by default.

But it's not enough to implement a small number of useful features. In particular, asynchronous effects can implement work-stealing and preemption, even within long CPU-bound computations. The tricky bit is not running the signal handler: `await_signal` does that nicely. The tricky bit is _pausing the running computation_ while the signal handler decides what to do, even if the running computation is CPU-bound work that does not perform effects. (It's much easier for I/O-bound work that's constantly stopping and starting, but preemption isn't really interesting there - cooperative scheduling works fine).

We already have an abstraction for paused computations, which can be resumed soon (like work-stealing wants to) or later (like preemption wants to), and it's continuations as used by effect handlers. On the other hand, it might not be a good idea to integrate these asynchronous effects into the `match` syntax, as that seems to elevate them to "normal programming tool", when for almost all problems an interface like `await_signal` is much better.

> My feeling is that if there has to be an asynchronous interrupt effect there should be a single one and it doesn't need to be a "timer" one. Simply an Interrupt which can be used by schedulers both for preemptive multitasking and cancellation.

The point of having multiple types of interrupt is so that you can pass (typed) data along with the interrupt, for instance when work-stealing. The alternative to this is putting said data in global or domain-local variables, which is a nightmare for synchronisation and composability.

@lpw25:

> The effect handler semantics would result in this signal being dropped. I already thought that these kind of "asynchronous effects" needed their own syntax and typing, but it seems clear they would need a slightly different semantics as well, and it is not entirely clear to me that the match statement is the right way to express this other semantics.

Yes, we'll need to do something like masking interrupts while executing a signal handler. I think that the one-shot continuations we use for effect handlers are exactly the right abstraction for a computation that has been paused in the middle of doing something and can be resumed now or later, but I'm starting to agree that `match` may not be the best way of expressing the handler side, and some primitive in `Sys` with a `match`-like signature might make more sense.
